name: Game compatibility report
description: a game compat report that will be merged to the list if it gets approved 
title: "[REPORT]: "
labels: [report]
body:
  - type: markdown
    attributes:
      value: |
        ### __Disclaimer:__
        Issue reports for the OPL app that was not downloaded from the [__Official OPL GitHub repository__](https://github.com/ps2homebrew/open-ps2-loader/releases) or [official Mega archive](https://mega.nz/folder/Ndwi1bAK#oLWNhH_g-h0p4BoT4c556A) are not accepted.
        Before posting the issue confirm that you meet the below requirements.

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: "Check before posting"
      options:
        - label: I have checked if a report of the same game, in the same test environment, is already included  

  - type: markdown
    attributes:
      value: |
        ##### please complete the following information:

  - type: dropdown
    id: itworks
    attributes:
      label: "game state"
      description: "how stable is the gameplay?"
      multiple: false
      options:
        - "Working"
        - "working with issues"
        - "barely working"
        - "imposible to play"
        - "doesn't even boot"
    validations:
      required: true

  - type: input
    id: console
    attributes:
      label: Console model
      description: you can see it on the console sticker or inside OSDSYS (press triangle on main menú)
      placeholder: "SCPH-????? / DTL-H????? / DESR-????"
    validations:
      required: true

  - type: input
    id: oplver
    attributes:
      label: "OPL version / revision"
      description: "you can see it on the About option from the settings menu (press start in game list)"
      placeholder: "eg: OPL stable 1.0.0 | OPL beta 1.1.0 1732"
    validations:
      required: true

  - type: input
    id: gametitle
    attributes:
      label: "Game title"
      placeholder: "eg: Predator Concrete jungle"
    validations:
      required: true

  - type: input
    id: regioncode
    attributes:
      label: "Game Region code (ID)"
      description: "OPL will show you this on it´s UI"
      placeholder: "eg: SLES_530.91"
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: "In which device have you performed the test?"
      multiple: false
      options:
        - USB
        - SMB
        - HDD
        - iLink
        - MX4SIO
    validations:
      required: true

  - type: dropdown
    id: image
    attributes:
      label: "what was the game format?"
      multiple: false
      options:
        - ISO
        - ZSO
        - UL
        - HDL ISO
        - HDL ZSO
    validations:
      required: true

  - type: checkboxes
    id: features 
    attributes:
      label: features
      description: "Wich features did you test?"
      options:
        - label: VMC
        - label: PADEMU
        - label: PADMACRO
        - label: IGR
        - label: GSM
    validations:
      required: false

  - type: dropdown
    id: compatmode
    attributes:
      label: "Compatibility modes"
      description: "if you had to apply compatibility modes to make it work, please specify below"
      multiple: true
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: comments about this report 
      description: Information about game performance 
      placeholder: "ie: audio is corrupted/game crashes when using ..."
    validations:
      required: false
