name: Game compatibility report
description: a game compat report that will be merged to the list if it gets approved
title: "[REPORT]: "
labels: [report]
body:
  - type: markdown
    attributes:
      value: |
        ### __Disclaimer:__
        Issue reports for the OPL app that was not downloaded from the [__Official OPL GitHub repository__](https://github.com/ps2homebrew/open-ps2-loader/releases) or [official Mega archive](https://mega.nz/folder/Ndwi1bAK#oLWNhH_g-h0p4BoT4c556A) are not accepted.
        Before posting the issue confirm that you meet the below requirements.

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: "Check before posting"
      options:
        - label: I have checked if a report of the same game, in the same test environment, is already included
        - label: I have tested all features from the feature list

  - type: markdown
    attributes:
      value: |
        ##### Please complete the following information:

  - type: dropdown
    id: gamestate
    attributes:
      label: "Gameplay status"
      description: "how stable is the gameplay?"
      multiple: false
      options:
        - "doesn't load"
        - "loads but imposible to play"
        - "Playable with minor issues"
        - "Playable with major issues"
        - "Fully playable"
    validations:
      required: true

  - type: input
    id: console
    attributes:
      label: Console model
      description: you can see it on the console sticker or inside OSDSYS (press triangle in the main menu)
      placeholder: "SCPH-????? / DTL-H????? / DESR-????"
    validations:
      required: true

  - type: input
    id: oplbetaver
    attributes:
      label: "BETA OPL revision number"
      description: "you can see it on the About option from the settings menu (press start in game list)"
      placeholder: "1732"
    validations:
      required: true

  - type: dropdown
    id: oplstablever
    attributes:
      label: "OPL stable version / revision (optional)"
      description: "in addition to the previous item, you can provide compatibility report for the stable opl versions"
      multiple: true
      options:
        - "v0.7"
        - "v0.8"
        - "v0.9"
        - "v0.9.1"
        - "v0.9.2"
        - "v0.9.3"
        - "v1.0.0"
        - "v1.1.0"
    validations:
      required: false

  - type: input
    id: gametitle
    attributes:
      label: Title
      description: "The game title"
      placeholder: "eg: Predator Concrete jungle"
    validations:
      required: true

  - type: input
    id: regioncode
    attributes:
      label: "Game Region code (ID)"
      description: "OPL will show you this on it's UI"
      placeholder: "eg: SLES_530.91"
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: "Devices checked"
      multiple: true
      options:
        - USB
        - SMB
        - HDD
        - iLink
        - MX4SIO
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: "Image format"
      description: "Game image format"
      multiple: false
      options:
        - ISO
        - ZSO
        - UL
    validations:
      required: true

  - type: dropdown
    id: media
    attributes:
      label: "Media"
      description: "Game image media (DVD9=Dual layer DVD)"
      multiple: false
      options:
        - DVD5
        - DVD9
        - CD
    validations:
      required: true

  - type: checkboxes
    id: features
    attributes:
      label: Features
      description: "Wich features did you test?"
      options:
        - label: VMC
        - label: PADEMU
        - label: PADMACRO
        - label: IGR
        - label: GSM

  - type: dropdown
    id: compatmode
    attributes:
      label: "Compatibility modes"
      description: "if you had to apply compatibility modes to make it work, please specify below"
      multiple: true
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
    validations:
      required: false

  - type: input
    id: comments
    attributes:
      label: Comments about this report
      description: Information about game performance
      placeholder: "ie: audio is corrupted/game crashes when using ..."
    validations:
      required: false
