name: process aproved workflow
on:
  issues:
    types:
      - labeled

jobs:
  create-PR:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: checkout v3
        uses: actions/checkout@v3

      - name: install required crap
        run: |
          sudo apt-get install -y --assume-yes dos2unix jq wget

      - name: ProcessData script execution
        run: |
          cd script
          ./ProcessData.sh ${{ github.event.issue.number }}

      - name: Create Pull Request
        id: prmaker
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "merge report #${{ github.event.issue.number }}"
          body: "merge report #${{ github.event.issue.number }}"
          title: "merge report #${{ github.event.issue.number }}"
          delete-branch: true
          branch-suffix: random
          add-paths: |
            List/*/*

      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Your issue was approved and transfered into a [__Pull Request__](${{ steps.prmaker.outputs.pull-request-url }})
            now it's awaiting a maintainer aproval to be merged into list
